{"name":"Docker","slug":"Docker","count":1,"postlist":[{"title":"Docker守护进程连接错误","uid":"11dfc50955afa32461ac370ac3e78a2c","slug":"2025-07-19-02","date":"2025-07-19T14:34:01.000Z","updated":"2025-07-21T05:30:57.003Z","comments":true,"path":"api/articles/2025-07-19-02.json","keywords":null,"cover":null,"text":"问题描述在使用 docker 时，发现 docker 守护进程出现连接错误，如下： 123[root@localhost ~]# docker restart ...","permalink":"/post/2025-07-19-02","photos":[],"count_time":{"symbolsCount":"15k","symbolsTime":"13 mins."},"categories":[{"name":"Docker","slug":"Docker","count":1,"path":"api/categories/Docker.json"}],"tags":[{"name":"Docker","slug":"Docker","count":1,"path":"api/tags/Docker.json"}],"author":{"name":"Reverse","slug":"blog-author","avatar":"/images/avatar.jpg","link":"/","description":"每一次的突破，都是自我超越的见证。","socials":{"github":"https://github.com/hyhacct","twitter":"","stackoverflow":"","wechat":"","qq":"","weibo":"","zhihu":"","csdn":"","juejin":"","customs":{}}},"feature":false}]}